### ISSUE TITLE
What does compiled output look like for web projects

### ISSUE THREAD

**Issue by petemill** [brave/leo#16]
If we wanted to consume leo components from other projects with minimal bundler / build configuration, what would that look like? What are some svelte examples to follow?

We would want to keep:
- Type safety and intellisense for react consumers (e.g. button/react.ts)
- Type safety and intellisense for svelte consumers (e.g. button/button.svelte)

**Comment by fallaciousreasoning** [comment]
I think #26 should solve this. It uses one of the internal Svelte projects ([svelte2tsx](https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx)) to generate type definitions as part of the build process.

**Comment by fallaciousreasoning** [comment]
A problem we have with this currently is that we compile Leo in consuming projects, which means that projects which use Leo need to depend on Svelte and PostCSS.

That said, maybe this is okay? We could solve by precompiling before publishing to NPM but there are definitely tradeoffs.

**Comment by AlanBreck** [comment]
What are the downsides to precompiling?

**Comment by fallaciousreasoning** [comment]
I guess we could get multiple copies of things? It's probably fine with Svelte though as the library gets compiled away. I guess the main one would be we need to remember to compile it 😆

**Comment by petemill** [comment]
One downside could be more difficult local development workflow if the directory structure differs between source and packaged npm

**Comment by fallaciousreasoning** [comment]
Presumably, if it compiled to a `./build` folder or something, we could point to that folder. It might make pointing to a Github repository harder though.
