### ISSUE TITLE
Button component layout

### ISSUE THREAD

**Issue by petemill** [brave/leo#2]
Properties (for react / svelte / wc):

```ts
interface LeoButtonProps {
  kind: "CTA" | "Primary" | "Secondary" | "Tertiary"
  size: "large" | "medium" | "small"
  isLoading: boolean
}

type LeoIconButtonProps = LeoButtonProps
```

note: don't want to use the following keys:
- `type`: buttons can define `type="submit"` for forms, etc
- `style`: confusing

Class names for css used by web-component (and by tailwind / non-js pages?):
- `leo-button`
- `leo-icon-button`
- `kind-[cta|primary|secondary|tertiary]`
- `size-[large|medium|small]`
- `is-loading`

**Comment by petemill** [comment]
Alternative I sometimes use:
```ts
interface Props {
  isPrimary: boolean
  isCTA: boolean
  isSecondary: boolean
  isTertiary: boolean
  isLarge: boolean
  isMedium: boolean
  isSmall: boolean
}
```

corresponding class names:
- `leo-button`
- `is-cta`
- `is-primary`
- `is-small`
- etc...

Feels a bit too much with the amount of variants

**Comment by fallaciousreasoning** [comment]
FWIW, I like having the separate size/kind properties. I think some other UI libraries use `variant` instead of `kind` but `kind` seems fine to me.

I dislike the idea of having separate booleans for each property because it means we could write this:


```tsx
<Button isSmall isLarge isPrimary isSecondary/> <!-- What does this button look like? -->
```

**Comment by AlanBreck** [comment]
I really like the color, and I think it would fit fine with Tailwind since they use that for variants (this like breakpoints, hover, focus, dark mode, etc.). Fine with either one, ultimately.

**Comment by fallaciousreasoning** [comment]
Closing this - we seem pretty well settled on `kind` now
