### ISSUE TITLE
Text field and dropdown updates

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#294]
Made changes to the components, listing them out here:
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?type=design&node-id=195%3A7599&t=bbULU5IpalI4gSaq-1

Note: this also applies to text areas

- Added new style: outline. This should be the default style
- Changed outline color from divider/subtle to divider/strong
- Tweaked the disabled state background
- Placeholder text now uses text/tertiary
- Padding changes within the text
- Stroke width for focus/active and error states is 1.5px. 
- Added "Large" variant

**Comment by petemill** [comment]
From @aguscruiz :
- Let's not have the Label change to blurple when the dropdown is open but instead let's apply the focused state (purple border) on the select
