### ISSUE TITLE
Add opacity to colors

### ISSUE THREAD

**Issue by petemill** [brave/leo#306]
@aguscruiz has stated that the transparency is intentional, so we need our values to reflect that.

CSS and Skia both need the alpha values

**Comment by AlanBreck** [comment]
Is the transparency supposed to be configurable? If so, the alpha could be a a css variable value on the token. This is what Tailwind does for their colors, and how it's configured for the tailwind tokens.

**Comment by petemill** [comment]
For these ones I don't think that is is meant to be configurable - it's part of the token.

**Comment by aguscruiz** [comment]
Yeah, not configurable in general. Just part of the token

**Comment by fallaciousreasoning** [comment]
For what it's worth, we can make them configurable pretty easily, if we expose a separate variable for the opacity. Is that worth doing, or is it just going to bloat the CSS file?

**Comment by aguscruiz** [comment]
I'm not sure, designers usually change a layer's opacity instead of the color when designing. The only cases are here in the variables. But if it's not too much problem, then why not, sure

**Comment by petemill** [comment]
Closing because
1) Designers can't change opacity when using variables
2) we already bring in the alpha (via `rgba()`) for variables which have alpha.

**Comment by boocmp** [comment]
In tokens/css/variables
![image](https://github.com/brave/leo/assets/73575789/a25434e6-aa19-422a-8e2d-c832fdda4267)

In tokens/skia/color.h
![image](https://github.com/brave/leo/assets/73575789/e85b7803-8d2a-4055-b677-e21f3d7a8f0a)

There is no alpha in colors.h

**Comment by fallaciousreasoning** [comment]
Good catch! We're pretty terrible at keeping these in sync. Reopening for Skia
