### ISSUE TITLE
Rename `brave-icon-debug-color.svg` file to `brave-icon-dev-color.svg`

### ISSUE THREAD

**Issue by simonhong** [brave/leo#393]
`debug` is not the proper channel name.
As `brave-icon-debug-color.svg` is used for development channel, `brave-icon-dev-color.svg` would be more proper file name.

**Comment by AlanBreck** [comment]
I believe @aguscruiz will have to make this change, and it will be automatically picked up in a new PR for the codebase.

**Comment by aguscruiz** [comment]
Done!

**Comment by simonhong** [comment]
@aguscruiz Thanks for quick fix! 👍🏼

**Comment by simonhong** [comment]
@fallaciousreasoning Please let me know when you bump leo.
I need to update brave-core for this file name change.
https://github.com/brave/brave-core/pull/20215/files#diff-4a7ab71a64ac5712bb35fb91782847039cf2def6ee9c3d64a7efa66562a99acfR288

**Comment by petemill** [comment]
@simonhong perhaps you can push to here https://github.com/brave/brave-core/pull/20263

**Comment by AlanBreck** [comment]
Can this be closed?

**Comment by simonhong** [comment]
Yup, we could close this.
