### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by petemill** [brave/leo#45]
### Serving / Requesting
We want to allow:
- Consumers to self-host all the .svg files so that they can reduce duplication among bundles (e.g. brave-core serving icons from chrome://resources/leo-icons/x.svg
  - Consumers could choose to only serve .svg files they are using, to conserve package size
  - Consumers could serve icons from a central URL but Leo JS from local bundles
- Consumers can define a custom library of .svg files, and get the benefits of a `LeoIconComponent`

All icons exist in repo as separate .svg files, e.g. `/leo/icons/xyz.svg`
`LeoIconComponent` fetches the file and renders the svg, adds css class to it.
Consumer passes in icon-name and 
```
<LeoIcon library="leo" label="" name="search" />
````

Take inspiration from https://shoelace.style/components/icon / https://github.com/shoelace-style/shoelace/tree/next/src/components/icon

### Benefits of `LeoIconComponent`
- Change fill / stroke to `currentColor` so it inherits `color` via css
- Restrict width and height to `--leo-icon-size` so that the icon fits in to containers, e.g. different button types
- Fetches and inlines

### What it won't do
- Accept custom color property, this should be cascaded through css, i.e. set `color: pink` on the custom element or container or anywhere. Same with `--leo-icon-size`.

**Comment by OAuthBringer** [comment]
@petemill Am I correct in interpreting that the `LeoIconComponent` won't accept any styling properties (thinking size etc) at all it is merely an API for the existing iconography and all styling related concerns are delegated to CSS?

**Comment by petemill** [comment]
@OAuthBringer that's correct - color and size would be provided via css inheritance. Anything else, like a border, spacing, etc would need to be provided by a container. What do you think?

**Comment by OAuthBringer** [comment]
@petemill I think it's a wise approach.  In my experience the path to hell is paved with props. Exposing the whole set of iconography in a single import with baked in theming support is quite a lot.

**Comment by petemill** [comment]
Need to decide naming convention so we know which ones can use currentColor and which have multiple icons

**Comment by petemill** [comment]
Need SVGO optimization strategy

**Comment by fallaciousreasoning** [comment]
I've started work on the component here https://github.com/brave/leo/pull/100
