### ISSUE TITLE
Component: Alert

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#47]
Inline or system alerts
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=195%3A5635

![image](https://user-images.githubusercontent.com/15734630/199497977-fd79102f-1f9c-45a2-bb0b-586c81254f98.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0
