### ISSUE TITLE
[Bug] Tooltip content "scrolls" when against an edge

### ISSUE THREAD

**Issue by benjaminknox** [brave/leo#477]
# What?

I noticed the tooltip content appears to "scroll" into line when opened against an edge of the browser.

https://github.com/brave/leo/assets/5668789/184df6a2-179c-4703-8893-16b75aa62918

This seems like a bug to me

**Comment by petemill** [comment]
This is either a duplicate or caused by https://github.com/brave/leo/issues/391 depending on how you look at it
