### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#48]
Regular button component:
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=278%3A12159

<img width="389" alt="image" src="https://user-images.githubusercontent.com/15734630/199498146-233bba6e-2151-448e-96c5-360652620c27.png">

**Comment by OAuthBringer** [comment]
Required for Creators 2.0

**Comment by OAuthBringer** [comment]
I'm not sure if this is functionally complete or not.

**Comment by fallaciousreasoning** [comment]
I think the colors might be slightly different, looking at https://leo.bravesoftware.com/

**Comment by AlanBreck** [comment]
Yeah, looks like CTA styling was replaced by Hero and uses a different gradient.

Were there other changes you're seeing, @fallaciousreasoning?

**Comment by fallaciousreasoning** [comment]
Nah, that was the only thing that jumped out at me

**Comment by fallaciousreasoning** [comment]
I'm closing this as completed, now the new variants have landed in https://github.com/brave/leo/pull/232
