### ISSUE TITLE
Update color rules for buttons and hover states

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#484]
### New color rules

Based on requirements from the design team, we'll need to be able to let the colors of the button change depending on different needs. Colors should be customizable to reflect different states

![image](https://github.com/brave/leo/assets/15734630/ae539ee7-aa1d-48da-b3b1-c20459552c1b)

### New hover states

This new set of customizations puts us into some trouble when it comes to hover states. @fallaciousreasoning were talking about using [-color mix](https://www.smashingmagazine.com/2022/06/simplify-color-palette-css-color-mix/) as a solution for the issue, with the following values:

Light mode: Add a mix of 20% black to the colors.
Dark mode: Add a mix of 20% white to the colors

<img width="1324" alt="image" src="https://github.com/brave/leo/assets/15734630/4ff5854d-cb64-462d-9eb4-9823de466796">

<img width="1338" alt="image" src="https://github.com/brave/leo/assets/15734630/781f8e6a-e9c8-4257-b8c7-c2e2b9ec8662">

**Comment by fallaciousreasoning** [comment]
Cool this should be quite an interesting change - I don't know if we can use `color mix` yet, as all browsers only added support in May 2023. @petemill wdyt? Alternatively, we could generate a palette from the color at build/run time?

**Comment by AlanBreck** [comment]
We could potentially do something similar, but use `hsl` instead of `color-mix`. The below is a little clunky, but we could maybe create a PostCSS plugin for a convenience function.

https://codepen.io/AlanBreck/pen/poGVEoL

**Comment by fallaciousreasoning** [comment]
@aguscruiz how do we handle `:focus` `:active`, `disabled` and `loading` states?

**Comment by aguscruiz** [comment]
Those states can remain they are now, I think
