### ISSUE TITLE
Component: Segmented control

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#50]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=4179%3A16474

![image](https://user-images.githubusercontent.com/15734630/199498318-b2545d06-5813-4ccc-86c7-afca0cc52b11.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0
