### ISSUE TITLE
Dropdown updates

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#514]
- [ ] Updated rounded corner values for each size to match button values
- [ ] Updated heights of the actual inputs to match button values

https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?type=design&node-id=195%3A7599&mode=design&t=VHhtLpJltP9ac2IA-1

**Comment by JuanJFrontDev** [comment]
Hello, I do not know if somebody took this already, but I would like to be assigned to it please.
