### ISSUE TITLE
Update to plain and plain faint button hover states

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#528]
Added a subtle background color to the plain buttons on hover, so they get a hint of the button shape when the mouse is hovering.

For the buttons that change color, the background should be:
- 5% of the text color in light mode _(The original text color, not the one darkened for hover)_
- 10% in dark mode 
- 10% in over images mode

https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?type=design&node-id=278%3A12159&mode=design&t=jTcaISJnJXqdPoYR-1

### Regular colors:
<img width="1032" alt="image" src="https://github.com/brave/leo/assets/15734630/c9b69529-c25d-477c-abf4-3a5ed75fdcff">

### Customized color example:
<img width="420" alt="image" src="https://github.com/brave/leo/assets/15734630/546a4313-2d29-4cc7-b488-3839577ea243">

**Comment by AlanBreck** [comment]
How will this impact `plain` and `plain-faint` icon only buttons?

**Comment by AlanBreck** [comment]
> 10% in over images mode

I don't believe we have an `images` mode. Correct, @fallaciousreasoning and @petemill?

**Comment by fallaciousreasoning** [comment]
We do not - it's not something we can detect programatically either

**Comment by aguscruiz** [comment]
I think I was on delululand when I thought we had created that set. Sorry!
