### ISSUE TITLE
Component: Input field / Text area / Dropdowns

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#54]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=195%3A7599

![image](https://user-images.githubusercontent.com/15734630/199498846-bca49e30-802f-48c1-bbcc-81a7b3a6b650.png)

**Comment by AlanBreck** [comment]
@aguscruiz, what's the difference between dropdowns here, and those in https://github.com/brave-experiments/leo/issues/55?
