### ISSUE TITLE
Component: Toggle

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#61]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=195%3A9190

![image](https://user-images.githubusercontent.com/15734630/199499436-7d632c65-f83b-4af8-8abb-8b26195bb3c1.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0
