### ISSUE TITLE
Component: Label

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#63]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=195%3A15172

![image](https://user-images.githubusercontent.com/15734630/199499597-151d1534-2ca7-4f0f-8ce7-3282c17ec861.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0
