### ISSUE TITLE
Component: Navigation dots

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#65]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=200%3A11392

![image](https://user-images.githubusercontent.com/15734630/199499953-abe03c31-cfc6-480f-bbf6-30f8592fa11a.png)

**Comment by fallaciousreasoning** [comment]
It'd be cool to use this on the New Tab Page for the Grid of sites (there's a similar control there but it would be great to be able to use Leo

**Comment by fallaciousreasoning** [comment]
Hey @aguscruiz I've just started implementing this and I have a couple of questions:
1. Can we make the hover state more obvious? Currently it's nearly identical to the Default state.
2. Should the pill (for the current dot) have a hover state or a `focus:visible` state? Interacting with it is a no-op.

**Comment by aguscruiz** [comment]
Looks great! Answering your questions:
1- Already fixed on Figma, let me know what you think
2- Also answered, I think it shouldn't have a hover state, but it should probably have a focus one.
3- That's what I was thinking, I would add an easing property to make it a bit smoother. `ease-in-out` should improve it a lot, let's try it out. And in general, ease-in-out should be the default easing I think (I'm working on drafting that spec)
