### ISSUE TITLE
Tooltip flashing - doesn't get content slotted immediately

### ISSUE THREAD

**Issue by petemill** [brave/leo#650]
The tooltip doesn't get its content slotted on the first frame. This can be observed by having content large enough to push the tooltip to underneath the trigger. You will notice (most of the time) that the tooltip pops up above the trigger with no content, then moves on the next frame to where it is meant to be with the correct size content being slotted in.

This doesn't present on svelte, only on web component versions.

**Comment by fallaciousreasoning** [comment]
Closing this, as I'm pretty sure I fixed this way back
