### ISSUE TITLE
[Variables]: A bunch of variables are changed/missing

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/leo#655]
@aguscruiz this means I can't update Nala in brave-core at the moment:

- `color-icon-default` is gone. Should this be migrated to `color-icon`?
- `color-icon-interactive` is gone. Not sure what to migrate this to
- `desktop` segment has been added to font tokens in the generated `tokens/css/index.ts` (@AlanBreck I think this might be on our end)
- systemFeedback text colors have disappeared - not sure how to migrate these
- `color-container-interactive` is gone - should this be `color-container-interactiveBackground` now?
- `color-divider-interactive` is gone
- `color-button-background` is gone. Should this be `color-interactive-buttonPrimaryBackground` now?

I think there are probably more but these ones seem to be the most common (probably on the order of hundreds of usages).

**Comment by fallaciousreasoning** [comment]
Okay, @AlanBreck the `desktop` segment seems to be missing because the files we need to import from has changed

**Comment by fallaciousreasoning** [comment]
More digging - looks like `npm` isn't installing the right version of the package for me :facepalm:

**Comment by AlanBreck** [comment]
So can this be closed?

**Comment by fallaciousreasoning** [comment]
Yup :smile:
