### ISSUE TITLE
Component: Progress ring

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#67]
https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=1611%3A13504

![image](https://user-images.githubusercontent.com/15734630/199500086-81d43ad7-9a40-4227-b9b8-19bd21e4e8fa.png)

**Comment by OAuthBringer** [comment]
Probably Required for Creators 2.0
