### ISSUE TITLE
Button Web Component doesn't treat "isDisabled" as a boolean type

### ISSUE THREAD

**Issue by petemill** [brave/leo#690]
This does not result in a disabled button:
```
<leo-button id="clickable" isDisabled>Disabled button</leo-button>
```

This does:
```
<leo-button id="clickable" isDisabled="anything">Disabled button</leo-button>
```

When telling a rendering framework like Polymer that the attribute is a boolean attribute, it will add the attribute (without a string value). This does not result in a disabled button.
Likewise when telling the rendering framework it's simply a string attribute, all buttons will be disabled, since "true" or "false" result in `isDisabled` being present.

**Comment by fallaciousreasoning** [comment]
:facepalm: I bet we're checking `!isDisabled` or something, and because the empty string is falsey....
