### ISSUE TITLE
Component: Navigation

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#72]
We have vertical and horizontal navigation
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%96%A5-Desktop-%26-Web?node-id=1021%3A17153

![image](https://user-images.githubusercontent.com/15734630/199500614-31cc6a61-a608-4a1e-b364-0d29a40fa023.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0
