### ISSUE TITLE
Incorrect token colours in dark mode

### ISSUE THREAD

**Issue by StephenHeaps** [brave/leo#753]
1) Text primary
    - Current `universal.variables.json` value shows `#1b1b1f`: https://github.com/brave/leo/blob/f773fced49436f62e431dea4b17a285b537dd7a0/src/tokens/universal.variables.json#L1259
    - Figma shows `#E3E3E8`

2) Text secondary
    - Current `universal.variables.json` value shows `#46464a`: https://github.com/brave/leo/blob/f773fced49436f62e431dea4b17a285b537dd7a0/src/tokens/universal.variables.json#L1264
    - Figma shows `#C7C7CC`

3) Container background 
    - Current `universal.variables.json` value shows: `#fafafb`: https://github.com/brave/leo/blob/f773fced49436f62e431dea4b17a285b537dd7a0/src/tokens/universal.variables.json#L1323
    - Figma shows `#111114`

**Comment by StephenHeaps** [comment]
@aguscruiz In Figma I was getting the hex colors from the Nala Design System / Universal / Color page: https://www.figma.com/design/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=2768-24473&m=dev

In [brave-core PR #24772](https://github.com/brave/brave-core/pull/24772/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L177-R177) we updated from [commit `765fc137fcd02d0ce54ee14ddbd38f7380b6d43a`](https://github.com/brave/leo/blob/765fc137fcd02d0ce54ee14ddbd38f7380b6d43a/src/tokens/universal.variables.json) to [commit `8f981cd78e484cd97348855350ab5ade2f3dc1db`](https://github.com/brave/leo/blob/8f981cd78e484cd97348855350ab5ade2f3dc1db/src/tokens/universal.variables.json)

In this update the json values for each of these colours changed in dark mode:
1) Text primary
From: https://github.com/brave/leo/blob/765fc137fcd02d0ce54ee14ddbd38f7380b6d43a/src/tokens/universal.variables.json#L1150-L1154

To: https://github.com/brave/leo/blob/8f981cd78e484cd97348855350ab5ade2f3dc1db/src/tokens/universal.variables.json#L1256-L1261

2) Text secondary
From: https://github.com/brave/leo/blob/765fc137fcd02d0ce54ee14ddbd38f7380b6d43a/src/tokens/universal.variables.json#L1155-L1158

To:
https://github.com/brave/leo/blob/8f981cd78e484cd97348855350ab5ade2f3dc1db/src/tokens/universal.variables.json#L1262-L1266

3) Container background
From: https://github.com/brave/leo/blob/765fc137fcd02d0ce54ee14ddbd38f7380b6d43a/src/tokens/universal.variables.json#L1208-L1212

To: https://github.com/brave/leo/blob/8f981cd78e484cd97348855350ab5ade2f3dc1db/src/tokens/universal.variables.json#L1320-L1325

These are the values that get read on iOS for `Color(braveSystemName: .textPrimary)` / `Color(braveSystemName: .textSecondary)` / `Color(braveSystemName: .containerBackground)` respectively. I think the Figma colours are fine, I think it's just an issue with this `universal.variables.json` file.

**Comment by aguscruiz** [comment]
Ah ok, got it! Thanks for the clarification

**Comment by aguscruiz** [comment]
cc @fallaciousreasoning then

**Comment by fallaciousreasoning** [comment]
Okay, I think this issue should only affect iOS & Android - in C++/CSS we use the aliased values, which were using the correct mode.
