### ISSUE TITLE
[Icons]: We need some new icons in brave-core

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/leo#824]
`database` and `database-off`
![image](https://github.com/user-attachments/assets/e6425338-2e4b-4f33-b961-e936c16f2b0e)

`v8optimizer`
![image](https://github.com/user-attachments/assets/fec8ac50-a713-4d5a-8605-813c4c8a0222)

`picture-in-picture-off`
![image](https://github.com/user-attachments/assets/2a80468b-35ed-48d4-a48c-7ea8c6d15d85)

`zoom-scroll` `zoom-scroll-off`
![image](https://github.com/user-attachments/assets/a33f8dd4-d6bd-49d7-acf2-88f8c715dc27)

**Comment by aguscruiz** [comment]
@fallaciousreasoning Added to nala:

- database
- database-delete
- database-off
- We already have picture-in-picture, to replace the chromium default one
- picture-in-picture-off
- zoom-scroll
- zoom-scroll-off

For the V8 one, I think we should probably keep the one they have, since it's a logo.
