### ISSUE TITLE
[Colors]: Secondary color should not look bad when used next to the primary color 

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/leo#838]
In Chromium, the Secondary color is used in dark mode in a bunch of tonal values - this does not look great
https://github.com/brave/brave-browser/issues/41125

We should change the Nala secondary color to something we can safely use by default :smile:

If we don't we're going to be going against the grain in Chromium, and its going to make our lives harder. 

Example screenshots:

![image](https://github.com/user-attachments/assets/b0076ce9-752e-4776-baf2-391feee0ebcf)
 
![image](https://github.com/user-attachments/assets/3c3e1a97-b371-4a2e-8e71-b3adcbf29abf)

**Comment by aguscruiz** [comment]
@fallaciousreasoning this one is gonna be a problem 😬.

Do you know if chromium is using the same value for primary/secondary in their themes? I can't really tell but it seems like it's a different shade of blue between primary/secondary. 

Good call on disabling the tonal in the meantime, but I don't really understand how chromium intends to use the primary/secondary combination there in just the outline of the buttons? That's super weird to me. I don't see how their color combinations would look ok either unless it's the same value

**Comment by fallaciousreasoning** [comment]
Yeah, I think they use a very similar color to their primary color as the secondary color:
![image](https://github.com/user-attachments/assets/81f64901-76e8-4852-996a-77cf51c3b80e)

![image](https://github.com/user-attachments/assets/df7a4d98-8742-496c-b7e2-2e095f309a6a)

![image](https://github.com/user-attachments/assets/da64dabb-2c41-4ad1-93f0-e8d2fdff165f)

To me it looks like they use a grayer version of the primary color

**Comment by fallaciousreasoning** [comment]
I'm going to ask in the Chromium slack whether this is deliberate but if it is we probably need to change the Nala secondary color or this is going to make using Nala in Brave extremely difficult. 

We could migrate the `Rorange` which is our current secondary color into `color-legacy-secondary` or `color-rorange` or something like that. It'll be a pain to migrate but at least we won't have to worry about things changing under us

**Comment by fallaciousreasoning** [comment]
Okay, looking a bit more at the Material UI theme builder, it seems like our colors should be a bit more coherent - there are a bunch of weird looking components when I use Blurple/Rorange:

![image](https://github.com/user-attachments/assets/15e2c43e-0169-446c-88d5-676785dff414)

A lot of stuff looks a bit ugly (especially in dark mode):
![image](https://github.com/user-attachments/assets/74fffcd5-08e6-40d3-8416-0e92761dbc14)

imo light mode doesn't look great either:
![image](https://github.com/user-attachments/assets/e9b18703-f91f-417c-95ab-340778463c36)


When I change the seed color, it automatically regenerates the secondary color as a less vibrant version of the primary color:

(purpleish)
![image](https://github.com/user-attachments/assets/40b85f97-2633-4f83-9ce0-9528f112d9e9)

(redish)
![image](https://github.com/user-attachments/assets/42d7b4b1-9d0b-4cd5-9cae-d0feb4dc8381)

I think we should migrate this semi-urgently sorry @aguscruiz

**Comment by fallaciousreasoning** [comment]
Fixed by https://github.com/brave/leo/pull/856
